### ISSUE TITLE
data to test nlp emojify

### ISSUE THREAD

**Issue by davidfombella** [ranmax123/datascience#1]
file = '../data/w2vec.6B.50d.txt'

Where can i find this txt?
Is this from kaggle?

I only find this file **glove.6B.50d.txt** but looking for **w2vec.6B.50d.txt**

https://www.kaggle.com/watts2/glove6b50dtxt#glove.6B.50d.txt

**Comment by ranmax123** [comment]
@davidfombella You need to convert from Glove format to Word 2 Vec format.
